# Generated by Django 4.2.7 on 2023-12-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_wathchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='wathchlist',
            new_name='watchlist',
        ),
    ]
