# Generated by Django 4.2.7 on 2023-12-15 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_creator_bid_bidder_listing_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='wathchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
