# Generated by Django 4.2.7 on 2023-12-15 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_date_alter_listing_wathchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestBidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestBidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
