# Generated by Django 4.2.7 on 2023-12-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_highestbidder'),
        ('auctions', '0015_remove_listing_creator'),
    ]

    operations = [
    ]
