# Generated by Django 4.2.7 on 2023-12-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_merge_20231216_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highestBidder',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
    ]
