# Generated by Django 4.2.7 on 2023-12-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_highestbidder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='wathchlist',
            new_name='watchlist',
        ),
    ]
