# Generated by Django 4.2.7 on 2023-12-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_bid_bidder_listing_highestbidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bidder',
            new_name='commenter',
        ),
    ]
